version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile.app
      context: .
    networks:
      - user-defined
    volumes:
      - .:/code
      - logvolume01:/logs
    ports:
      - 4000:${PORT}
    restart: always
    depends_on:
      - db
  db:
    build:
      dockerfile: Dockerfile.db
      context: .
    networks:
      - user-defined
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
volumes:
  logvolume01: {}
  postgres: {}
networks:
  user-defined:
    driver: bridge
